projects:
  prisma:
    schemaPath: packages/prisma/prisma.graphql
    extensions:
      prisma: packages/prisma/prisma.yml
  backroom:
    endpoint: http://localhost:4000
    schemaPath: packages/backroom/src/backroom.graphql
